-- Fase 12.8: Web Push Subscriptions
-- Migration para armazenar inscrições de Web Push (aparelhos que recebem notificações)
-- Data: 20/07/2026
-- Status: ✅ EXECUTADA EM SUPABASE

CREATE TABLE IF NOT EXISTS time_tasks_push_subscriptions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users ON DELETE CASCADE,
  endpoint text NOT NULL UNIQUE,
  auth text NOT NULL,
  p256dh text NOT NULL,
  user_agent text,
  created_at timestamp DEFAULT now()
);

-- Row Level Security (RLS)
ALTER TABLE time_tasks_push_subscriptions ENABLE ROW LEVEL SECURITY;

-- Política 1: Usuários veem apenas suas próprias inscrições
CREATE POLICY "Users see own push subscriptions"
  ON time_tasks_push_subscriptions FOR SELECT
  USING (auth.uid() = user_id);

-- Política 2: Usuários podem inserir suas próprias inscrições
CREATE POLICY "Users insert own push subscriptions"
  ON time_tasks_push_subscriptions FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Política 3: Usuários podem deletar suas próprias inscrições
CREATE POLICY "Users delete own push subscriptions"
  ON time_tasks_push_subscriptions FOR DELETE
  USING (auth.uid() = user_id);

-- Comentários
COMMENT ON TABLE time_tasks_push_subscriptions IS
  'Armazena endpoints de Web Push de navegadores inscritos. Cada linha = 1 aparelho inscrito';
COMMENT ON COLUMN time_tasks_push_subscriptions.endpoint IS
  'URL unique do navegador para enviar notificação push (gerada automaticamente pelo browser)';
COMMENT ON COLUMN time_tasks_push_subscriptions.auth IS
  'Token de autenticação do push (generated by browser - required for encryption)';
COMMENT ON COLUMN time_tasks_push_subscriptions.p256dh IS
  'Chave de criptografia P-256 (generated by browser - required for ECDH)';
COMMENT ON COLUMN time_tasks_push_subscriptions.user_agent IS
  'Identificação do navegador/dispositivo (ex: Mozilla/5.0... Safari...)';

-- Índice para queries rápidas por user_id
CREATE INDEX IF NOT EXISTS idx_push_subscriptions_user_id
  ON time_tasks_push_subscriptions(user_id);
