-- Fase 12.8: Web Push Subscriptions
-- Tabela para armazenar inscrições de Web Push (aparelhos que recebem notificações)
-- Data: 20/07/2026

CREATE TABLE IF NOT EXISTS time_tasks_push_subscriptions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users ON DELETE CASCADE,
  endpoint text NOT NULL,
  auth text NOT NULL,
  p256dh text NOT NULL,
  user_agent text,
  created_at timestamp DEFAULT now(),
  updated_at timestamp DEFAULT now(),

  CONSTRAINT push_subscriptions_endpoint_unique UNIQUE (endpoint),
  CONSTRAINT push_subscriptions_user_endpoint UNIQUE (user_id, endpoint)
);

-- Índices
CREATE INDEX IF NOT EXISTS idx_push_subscriptions_user_id
  ON time_tasks_push_subscriptions(user_id);
CREATE INDEX IF NOT EXISTS idx_push_subscriptions_created_at
  ON time_tasks_push_subscriptions(created_at DESC);

-- Row Level Security (RLS)
ALTER TABLE time_tasks_push_subscriptions ENABLE ROW LEVEL SECURITY;

-- Política 1: Usuários só veem suas próprias inscrições
CREATE POLICY IF NOT EXISTS "Users see own push subscriptions"
  ON time_tasks_push_subscriptions
  FOR SELECT
  USING (auth.uid() = user_id);

-- Política 2: Usuários só podem inserir suas próprias inscrições
CREATE POLICY IF NOT EXISTS "Users insert own push subscriptions"
  ON time_tasks_push_subscriptions
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Política 3: Usuários só deletam suas próprias inscrições
CREATE POLICY IF NOT EXISTS "Users delete own push subscriptions"
  ON time_tasks_push_subscriptions
  FOR DELETE
  USING (auth.uid() = user_id);

-- Comentários
COMMENT ON TABLE time_tasks_push_subscriptions IS
  'Armazena endpoints de Web Push de aparelhos inscritos. Cada linha = 1 aparelho';

COMMENT ON COLUMN time_tasks_push_subscriptions.endpoint IS
  'URL unique do navegador para enviar notificação (gerada pelo browser)';

COMMENT ON COLUMN time_tasks_push_subscriptions.auth IS
  'Token de autenticação do push (generated by browser)';

COMMENT ON COLUMN time_tasks_push_subscriptions.p256dh IS
  'Chave de criptografia (generated by browser)';

COMMENT ON COLUMN time_tasks_push_subscriptions.user_agent IS
  'Identificação do navegador/dispositivo (ex: Mozilla/5.0...)';
